services:
  web:
    container_name: xstandardanwendung
    build:
      context: .
    ports:
      - "${WEB_PORT:-8000}:${WEB_PORT:-8000}"
    volumes:
      - ./app:/app
    environment:
      DEBUG: ${DEBUG:-1}
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      WEB_HOST: ${WEB_HOST:-0.0.0.0}
      WEB_PORT: ${WEB_PORT:-8000}
      APP_PATH: ${APP_PATH:-}
      LANGUAGE_CODE: ${LANGUAGE_CODE:-en-en}
      TZ: ${TZ:-UTC}
