# Generated by Django 6.0.6 on 2026-06-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBescheidUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=80)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('municipality', models.CharField(blank=True, max_length=255)),
                ('tax_period', models.CharField(blank=True, max_length=255)),
                ('amount_due', models.CharField(blank=True, max_length=100)),
                ('payment_type', models.CharField(blank=True, max_length=100)),
                ('trade_tax_assessment_amount', models.CharField(blank=True, max_length=100)),
                ('assessment_rate', models.CharField(blank=True, max_length=100)),
                ('due_dates', models.TextField(blank=True)),
                ('advance_payments', models.JSONField(blank=True, default=list)),
                ('summary_items', models.JSONField(blank=True, default=list)),
                ('result_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
